on:
  push:
    branches: [master]
    paths-ignore:
      - "**/README.md"
  pull_request:
    branches: [master]
    paths-ignore:
      - "**/README.md"

name: Test CI by GitHub Actions
jobs:
  build:
    name: Build apk & ipa
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
          cache: "gradle"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.5"
          channel: "stable"
          cache: true

      - name: Check Flutter verison
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Test
        run: flutter test

      - name: Build apk
        run: flutter build apk -t lib/app/main_dev.dart --flavor=dev

      - uses: actions/upload-artifact@v3
        with:
          path: "build/app/outputs/flutter-apk/*.apk"

      - name: Build ipa
        run: flutter build ios --no-codesign -t lib/app/main_dev.dart --flavor=dev

      - uses: actions/upload-artifact@v3
        with:
          path: "build/ios/iphoneos/*.app"
